name: tsp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - numba=0.60.0
  - numpy=1.26.4
  - numpydoc=1.7.0
  - matplotlib=3.10.0
  - matplotlib-inline=0.1.6
  - glob2=0.7
  - importlib-resources=6.4.5
  - importlib-metadata=8.5.0
  - pip
  - pip:
      - dearpygui==2.0.0
      - jschon==0.11.1
      - numba-progress==1.1.0
      - opencv-contrib-python==4.5.5.64
